# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: kubernetes
name: build-image

steps:
  - name: test
    image: rust:1-alpine3.15
    commands:
    - cargo test

  - name: docker
    image: plugins/docker
    settings:
      repo: dasbaumwolltier/simple-repository-manager
      tags: $(DRONE_TAG), latest
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password

trigger:
  branch:
  - release
  event:
  - tag
