# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: kubernetes
name: release

steps:
  - name: fetch dependencies
    image: rust:1-alpine3.15
    commands:
    - cargo fetch

  - name: test
    image: rust:1-alpine3.15
    commands:
    - apk add --no-cache musl-dev
    - cargo test

  - name: docker
    image: plugins/docker
    settings:
      repo: dasbaumwolltier/simple-repository-manager
      tags: latest
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password

trigger:
  branch:
    - release
