# yaml-language-server: $schema=https://json.schemastore.org/drone.json

kind: pipeline
type: kubernetes
name: release

steps:
  - name: test and build
    image: dasbaumwolltier/rust-musl-builder
    commands:
      - ls -la
      - cargo build --release
      - cargo test --release
      - echo -n "latest,$(cat Cargo.toml| grep version | cut -d' ' -f3 | tr -d '"')" | tee .tags

  - name: docker
    image: plugins/docker
    settings:
      repo: dasbaumwolltier/simple-repository-manager
      mtu: 1400
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password

trigger:
  branch:
    - release
