repositories:
  - name: archlinux
    type: file
#    path: /data/archlinux
    path: /tmp
    permissions:
      - username: archlinux
        permission: write
      - anonymous: true
        permission: read
users:
  - username: archlinux
    password: $2y$10$UsyT8mU1K8S0MopmfX246uOzqdKDrkI9J1NFcWEfBQI0kcvWtbPN2